blog/urls.py
from django.urls import path, reverse_lazy
from . import views
from .feeds import LatestPostsFeed
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('change-password/', login_required(auth_views.PasswordChangeView.as_view(template_name='blog/password_change_form.html',success_url=reverse_lazy('blog:change-password-done'))), name='change-password'),
    path('change-password/done/', login_required(auth_views.PasswordChangeDoneView.as_view(template_name = 'blog/password_change_done.html')), name='change-password-done'),
    
    
    path("reset-password/", auth_views.PasswordResetView.as_view(template_name='blog/password_reset_form.html',email_template_name='blog/password_reset_email.html',
                                                                 subject_template_name='blog/password_reset_subject.txt',success_url=reverse_lazy('blog:password_reset_done')), name="reset_password"),
    path("reset-password/done/", auth_views.PasswordResetDoneView.as_view(template_name='blog/password_reset_done.html'), name="password_reset_done"),
    path("reset-password-confirm/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name='blog/password_reset_confirm.html',success_url=reverse_lazy('blog:password_reset_complete')), name="password_reset_confirm"),
    path('reset-password/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='blog/password_reset_complete.html'),name='password_reset_complete'),

    path('register/',views.register ,name='register'),

    
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('addpost/', views.add_post, name='add_post'),
    path('edit/', views.edit, name='edit'),
   

]

mySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path("social-auth/", include('social_django.urls', namespace='social')),
    path("images/", include('images.urls', namespace='images')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from taggit.managers import TaggableManager
from django.conf import settings


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish']),]

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail',
        args=[self.publish.year,
              self.publish.month,
              self.publish.day,
              self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']),]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='user/%Y/%m/%d/', blank=True)

    def __str__(self) -> str:
        return f'Profile of {self.user.username}'
    
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created , **kwargs):
#     if created:
#         Profile.objects.create(user=instance)


# @receiver(post_save, sender=User)
# def save_user_receiver(sender, instance ,**kwargs):
#     instance.profile.save()
    

    

blog/forms.py
from django import forms
from .models import Comment, Post, Profile
from django.contrib.auth.models import User

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length= 25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)



class UserRegisterationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Password don't match.")
        return cd['password2']
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use.')
        return data
    

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Email already in use.')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']


    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from .models import Post, Comment, Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm, AddPostForm, LoginForm, UserRegisterationForm, UserEditForm, ProfileEditForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')
            return render(request, 'blog/search.html', {'form':form, 'query':query, 'results':results})
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/list.html', {'posts':posts, 'tag':tag,'form':form, 'query':query, 'results':results})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED,slug=post, publish__year=year, publish__month=month,
                                publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    return render(request, 'blog/detail.html', {'post':post,'comments': comments,'form': form,'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status = Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read" \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'snchorsiya008@gmail.com',
                      [cd['to']])
            sent = True
            print('Email Sned:', sent)
    else:
        form = EmailPostForm()
    return render(request, 'blog/share.html', {'post':post, 'form':form, 'sent':sent })


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
 # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
 # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
 # Assign the post to the comment
        comment.post = post
 # Save the comment to the database
        comment.save()
    return render(request, 'blog/comment.html',{'post': post,'form': form, 'comment': comment})



def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector, search_query)).filter(search=search_query).order_by('-rank')

    return render(request, 'blog/search.html', {'form':form, 'query':query, 'results':results})

@login_required
def add_post(request):
    form = AddPostForm()
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:post_list')
        
    return render(request, 'blog/addpost.html', {'form':form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username = cd['username'], password = cd['password'])
            if user is not None:
                  if user.is_active: 
                    login(request,user)
                    return redirect('blog:post_list')
            else:
                    return HttpResponse("Disable Account")
        else:
            return HttpResponse("Invalid Login")
    else:
        form = LoginForm()
    
    return render(request, 'blog/login.html', {'form':form})


@login_required
def user_logout(request):
    logout(request)
    return redirect("blog:login")


def register(request):
    if request.method == 'POST':
        user_form = UserRegisterationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            existing_profile = Profile.objects.filter(user=new_user).first()
            if existing_profile:
                print('Profile already exist:')
            else:
                Profile.objects.create(user=new_user)
            return render(request,'blog/register_done.html', {'new_user':new_user})
        
    else:
        user_form = UserRegisterationForm()
    return render(request, 'blog/register.html', {'user_form':user_form})


@login_required
def edit(request):
  if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
             user_form.save()
             profile_form.save()
             messages.success(request, 'Profile updated successfully')
             return redirect('blog:post_list')
        else:
            messages.error(request, 'Error updating your profile')
  else:
      user_form = UserEditForm(instance=request.user)
      profile_form = ProfileEditForm(instance=request.user.profile)
  return render(request,'blog/edit.html',{'user_form': user_form,'profile_form': profile_form})


    

blog/templates/blog/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include "blog/comment_form.html" %}
{% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
 {{ form.as_p }}
 {% csrf_token %}
 <p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<p>
    <a href="{% url "blog:post_share" post.id %}">
        Share this post
    </a>
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments.</p>
{% endfor %}
<a href="{% url 'blog:post_list' %}">
    Go back to the Post
</a>

{% include "blog/comment_form.html" %}
{% endblock %}

blog/templates/blog/edit.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Edit your account{% endblock %}
{% block content %}
<h1>Edit your account</h1>
<p>You can edit your account using the following form:</p>
<form method="post" enctype="multipart/form-data/">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.first_name|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.email|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{profile_form.date_of_birth|as_crispy_field}}
        </div>
        <br>
        <br>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{profile_form.photo|as_crispy_field}}
        </div>

    </div>
    <br>

    <div class="content">
        <button type="submit" style="display: block; margin: 0 auto;" class="btn btn-success">Save changes</button>
    </div>


</form>
{% endblock %}

blog/templates/blog/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block content %}

<h1>User Login</h1>
<p>
    Please, use the following form to log-in. 
    If you don't have an account <a href="{% url "blog:register" %}">register here</a>.
   </p>
   
<form method="POST">
    {% csrf_token %}

    <div class="form-row">
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{form.username|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{form.password|as_crispy_field}}
        </div>
        
    </div>
    <br>
    <!-- <table>{{ form.as_table }}</table> -->
    <div class="content">
        <button type="submit" style="display: block; margin: 0 auto;" class="btn btn-success">Login</button>
        </div>


</form>



<div class="social">
    <ul>
    <li class="facebook">
    <a href="{% url "social:begin" "facebook" %}">
    Sign in with Facebook
    </a>
    </li>
    <li class="twitter">
        <a href="{% url "social:begin" "twitter" %}">
        Sign in with Twitter
        </a>
        </li>
        <li class="google">
            <a href="{% url "social:begin" "google-oauth2" %}">
            Sign in with Google
            </a>
            </li>
    </ul>
    </div>
    
<br>
<br>
<p>
    <a href="{% url "blog:reset_password" %}">
        Forgotten your password?
        </a>
    </p>

{% endblock %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

blog/templates/blog/password_reset_complete.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Password reset{% endblock %}
{% block content %}
 <h1>Password set</h1>
 <p>Your password has been set. You can <a href="{% url "blog:login" %}">log in 
now</a></p>
{% endblock %}

blog/templates/blog/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>

{% if validlink %}

<p>Please enter your new password twice:</p>

<form method="post">
    
    {% csrf_token %}

    <div class="form-row">
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{ form.new_password1|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{ form.new_password2|as_crispy_field}}
        </div>
    </div>
    <br>
    <div class="content">
        <button type="submit" style="display: block; margin: 0 auto;" class="btn btn-success">Change my password</button>
        </div>
    </form>
    {% else %}
    <p>The password reset link was invalid, possibly because it has already 
   been used. Please request a new password reset.</p>
    {% endif %}
   {% endblock %}

blog/templates/blog/password_reset_done.html
{% extends "blog/base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}

<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered the address 
you registered with.</p>
{% endblock %}

blog/templates/blog/password_reset_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Rest your Password {% endblock %}

{% block content %}

<h1>Forgotten your Password</h1>
<p>Enter your e-mail address to obtain a new Password</p>

<form action="" method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{ form.email|as_crispy_field}}
        </div>
    </div>
    <br>
    <div class="content mb-0">
        <button type="submit" style="display: block; margin: 0 auto;" class="btn btn-success">Send e-mail</button>
    </div>

</form>

{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}
{% block content %}
<h1>Create an account</h1>
<p>
    Please, use the following form to log-in. 
    If you have an account <a href="{% url "blog:login" %}">login here</a>.
   </p>

<form method="POST">
    {% csrf_token %}
    
    <div class="form-row">
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.username|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.first_name|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.email|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.password|as_crispy_field}}
        </div>
        <div class="form-group col-md-7 mb-0" style="display: block; margin: 0 auto;">
            {{user_form.password2|as_crispy_field}}
        </div>
        
    </div>
    <br>
    <!-- <table>{{ form.as_table }}</table> -->
    <div class="content">
        <button type="submit" style="display: block; margin: 0 auto;" class="btn btn-success">Create my account</button>
        </div>


</form>
<!-- <br>
<br>
<p>
    <a href="{% url "blog:reset_password" %}">
        Forgotten your password?
        </a>
    </p> -->

{% endblock %}

blog/templates/blog/register_done.html
{% extends "blog/base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
 <h1>Welcome {{ new_user.first_name }}!</h1>
 <p>
 Your account has been successfully created. 
 Now you can <a href="{% url "blog:login" %}">log in</a>.
 </p>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{{ post.body|markdown|truncatewords_html:12 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}